import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { defineConfig } from 'vitest/config'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

export default defineConfig({
  resolve: {
    alias: {
      'smart-app-banner': path.resolve(__dirname, 'src/__tests__/mocks/smart-app-banner.js')
    }
  },
  esbuild: {
    loader: 'jsx',
    include: /src\/.*\.jsx?$/,
    exclude: []
  },
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: './src/setupTests.js',
    include: ['src/**/*.{test,spec}.{js,jsx,ts,tsx}'],
    css: false,
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html', 'lcov'],
      reportsDirectory: './coverage',
      // Interim: include grows per TEST_BATCH_REGISTRY.md batches.
      // Final (ship): must list ALL testable units (~210) at ≥70% avg — not this subset only.
      include: [
        'src/utils/**/*.{js,jsx}',
        'src/constants/**/*.{js,jsx}',
        'src/webStrategy/**/*.{js,jsx}',
        'src/sdk/lib/models/Model.js',
        'src/sdk/lib/models/Order.js',
        'src/sdk/lib/models/Cart.js',
        'src/sdk/lib/models/Business.js',
        'src/sdk/lib/models/Category.js',
        'src/sdk/lib/models/Address.js',
        'src/sdk/lib/models/Config.js',
        'src/sdk/lib/models/User.js',
        'src/sdk/lib/models/Product.js',
        'src/sdk/lib/models/Page.js',
        'src/sdk/lib/models/Menu.js',
        'src/sdk/lib/models/Language.js',
        'src/sdk/lib/models/Translation.js',
        'src/sdk/lib/models/OrderOption.js',
        'src/sdk/lib/models/OrderMessage.js',
        'src/sdk/lib/models/City.js',
        'src/sdk/lib/models/Country.js',
        'src/sdk/lib/models/Controls.js',
        'src/sdk/lib/models/DriversGroups.js',
        'src/sdk/lib/models/DriverLocations.js',
        'src/sdk/lib/models/PaymentCards.js',
        'src/sdk/lib/models/ValidationField.js',
        'src/sdk/lib/classes/Pagination.js',
        'src/sdk/lib/classes/ApiResponse.js',
        'src/sdk/lib/classes/ApiBase.js',
        'src/sdk/lib/classes/Ordering.js',
        'src/sdk/lib/classes/ApiCart.js',
        'src/sdk/lib/classes/ApiUser.js',
        'src/sdk/lib/classes/ApiOrder.js',
        'src/sdk/lib/classes/ApiConfig.js',
        'src/sdk/lib/classes/ApiBusiness.js',
        'src/sdk/lib/classes/ApiSystem.js',
        'src/contexts/ToastContext/**/*.{js,jsx}',
        'src/contexts/EventContext/**/*.{js,jsx}',
        'src/components/Emitter/**/*.{js,jsx}',
        'src/components/OrderTypeControl/**/*.{js,jsx}',
        'src/components/Analitycs/**/*.{js,jsx}',
        'src/components/BaseComponent/**/*.{js,jsx}',
        'src/components/FloatingButton/**/*.{js,jsx}',
        'src/components/ProductShare/**/*.{js,jsx}',
        'src/components/SmartAppBanner/**/*.{js,jsx}',
        'src/components/ExamineClick/**/*.{js,jsx}',
        'src/components/GpsButton/**/*.{js,jsx}',
        'src/components/PageBanner/**/*.{js,jsx}',
        'src/components/DragAndDrop/**/*.{js,jsx}',
        'src/components/LanguageSelector/**/*.{js,jsx}',
        'src/components/LogoutAction/**/*.{js,jsx}',
        'src/components/PlaceSpot/**/*.{js,jsx}',
        'src/components/Popup/**/*.{js,jsx}',
        'src/components/WebsocketStatus/**/*.{js,jsx}',
        'src/components/Contacts/**/*.{js,jsx}',
        'src/components/LoginForm/**/*.{js,jsx}',
        'src/components/SignupForm/**/*.{js,jsx}',
        'src/components/ForgotPasswordForm/**/*.{js,jsx}',
        'src/components/ResetPassword/**/*.{js,jsx}',
        'src/components/LoginGuest/**/*.{js,jsx}',
        'src/components/Sessions/**/*.{js,jsx}',
        'src/components/UserVerification/**/*.{js,jsx}',
        'src/components/QueryLoginSpoonity/**/*.{js,jsx}',
        'src/components/GoogleLoginButton/**/*.{js,jsx}',
        'src/components/FacebookLoginButton/**/*.{js,jsx}',
        'src/components/AppleLogin/**/*.{js,jsx}',
        'src/components/FirebaseGoogleLoginButton/**/*.{js,jsx}',
        'src/components/GoogleIdentity/**/*.{js,jsx}',
        'src/components/ReCaptcha/**/*.{js,jsx}',
        'src/components/AddressForm/**/*.{js,jsx}',
        'src/components/AddressList/**/*.{js,jsx}',
        'src/components/AddressDetails/**/*.{js,jsx}',
        'src/components/PhoneAutocomplete/**/*.{js,jsx}',
        'src/components/GoogleAutocompleteInput/**/*.{js,jsx}',
        'src/components/BusinessList/**/*.{js,jsx}',
        'src/components/BusinessSearchList/**/*.{js,jsx}',
        'src/components/BusinessController/**/*.{js,jsx}',
        'src/components/BusinessInformation/**/*.{js,jsx}',
        'src/components/BusinessBasicInformation/**/*.{js,jsx}',
        'src/components/BusinessTypeFilter/**/*.{js,jsx}',
        'src/components/BusinessSortControl/**/*.{js,jsx}',
        'src/components/SingleBusinessCard/**/*.{js,jsx}',
        'src/components/BusinessesMap/**/*.{js,jsx}',
        'src/components/LocationsMap/**/*.{js,jsx}',
        'src/components/BusinessMenuListing/**/*.{js,jsx}',
        'src/components/BusinessProductsCategories/**/*.{js,jsx}',
        'src/components/BusinessProductsSearch/**/*.{js,jsx}',
        'src/components/ProductsList/**/*.{js,jsx}',
        'src/components/ProductsListing/**/*.{js,jsx}',
        'src/components/StoreProductList/**/*.{js,jsx}',
        'src/components/BusinessAndProductList/**/*.{js,jsx}',
        'src/components/MenuControl/**/*.{js,jsx}',
        'src/components/ProductComponent/**/*.{js,jsx}',
        'src/components/ProductForm/**/*.{js,jsx}',
        'src/components/ProductOption/**/*.{js,jsx}',
        'src/components/ProductOptionSuboption/**/*.{js,jsx}',
        'src/components/ProductIngredient/**/*.{js,jsx}',
        'src/components/ProductItemAccordion/**/*.{js,jsx}',
        'src/components/SingleProductCard/**/*.{js,jsx}',
        'src/components/ReviewProduct/**/*.{js,jsx}',
        'src/components/ProductImages/**/*.{js,jsx}',
        'src/components/Cart/**/*.{js,jsx}',
        'src/components/Checkout/**/*.{js,jsx}',
        'src/components/MultiCheckout/**/*.{js,jsx}',
        'src/components/MultiCartCreate/**/*.{js,jsx}',
        'src/components/MultiCartsPaymethodsAndWallets/**/*.{js,jsx}',
        'src/components/CartStoresListing/**/*.{js,jsx}',
        'src/components/CouponControl/**/*.{js,jsx}',
        'src/components/UpsellingPage/**/*.{js,jsx}',
        'src/components/PaymentOptions/**/*.{js,jsx}',
        'src/components/PaymentOptionCash/**/*.{js,jsx}',
        'src/components/PaymentOptionStripe/**/*.{js,jsx}',
        'src/components/PaymentOptionStripeDirect/**/*.{js,jsx}',
        'src/components/PaymentOptionStripeLink/**/*.{js,jsx}',
        'src/components/PaymentOptionStripeRedirect/**/*.{js,jsx}',
        'src/components/PaymentOptionPaypal/**/*.{js,jsx}',
        'src/components/PaymentOptionSquare/**/*.{js,jsx}',
        'src/components/PaymentOptionWallet/**/*.{js,jsx}',
        'src/components/PaymethodList/**/*.{js,jsx}',
        'src/components/StripeElementsForm/**/*.{js,jsx}',
        'src/components/WalletList/**/*.{js,jsx}',
        'src/components/OrderList/**/*.{js,jsx}',
        'src/components/OrderListGroups/**/*.{js,jsx}',
        'src/components/OrderDetails/**/*.{js,jsx}',
        'src/components/OrderVerticalList/**/*.{js,jsx}',
        'src/components/OrderChange/**/*.{js,jsx}',
        'src/components/OrderReview/**/*.{js,jsx}',
        'src/components/MyOrders/**/*.{js,jsx}',
        'src/components/MyOrdersList/**/*.{js,jsx}',
        'src/components/SingleOrderCard/**/*.{js,jsx}',
        'src/components/NewOrderNotification/**/*.{js,jsx}',
        'src/components/MultiOrdersDetails/**/*.{js,jsx}',
        'src/components/OrdersControlFilters/**/*.{js,jsx}',
        'src/components/DriverList/**/*.{js,jsx}',
        'src/components/DriverTips/**/*.{js,jsx}',
        'src/components/ReviewDriver/**/*.{js,jsx}',
        'src/components/ReviewCustomer/**/*.{js,jsx}',
        'src/components/Messages/**/*.{js,jsx}',
        'src/components/MapView/**/*.{js,jsx}',
        'src/components/GoogleMaps/**/*.{js,jsx}',
        'src/components/MainSearch/**/*.{js,jsx}',
        'src/components/SearchOptions/**/*.{js,jsx}',
        'src/components/AnalyticsSegment/**/*.{js,jsx}',
        'src/components/FacebookPixel/**/*.{js,jsx}',
        'src/components/GoogleConversion/**/*.{js,jsx}',
        'src/components/CmsContent/**/*.{js,jsx}',
        'src/components/PromotionsController/**/*.{js,jsx}',
        'src/components/BusinessReviews/**/*.{js,jsx}',
        'src/components/BusinessReservation/**/*.{js,jsx}',
        'src/components/FavoriteList/**/*.{js,jsx}',
        'src/components/ProfessionalInfo/**/*.{js,jsx}',
        'src/components/SingleProfessionalCard/**/*.{js,jsx}',
        'src/components/ProjectForm/**/*.{js,jsx}',
        'src/components/UserFormDetails/**/*.{js,jsx}',
        'src/components/MomentOption/**/*.{js,jsx}',
        'src/components/GiftCard/**/*.{js,jsx}',
        'src/components/OrdersDashboardComponents/DashboardBusinessList/**/*.{js,jsx}',
        'src/components/OrdersDashboardComponents/DashboardOrdersList/**/*.{js,jsx}',
        'src/components/OrdersDashboardComponents/OrdersManage/**/*.{js,jsx}',
        'src/components/OrdersDashboardComponents/OrdersFilter/**/*.{js,jsx}',
        'src/components/OrdersDashboardComponents/OrderDetails/**/*.{js,jsx}',
        'src/components/OrdersDashboardComponents/CustomOrderDetails/**/*.{js,jsx}',
        'src/components/OrdersDashboardComponents/OrderNotification/**/*.{js,jsx}',
        'src/components/OrdersDashboardComponents/UsersList/**/*.{js,jsx}',
        'src/components/OrdersDashboardComponents/UserFormDetails/**/*.{js,jsx}',
        'src/components/OrdersDashboardComponents/DriversList/**/*.{js,jsx}',
        'src/components/OrdersDashboardComponents/Messages/**/*.{js,jsx}',
        'src/components/OrdersDashboardComponents/WebsocketStatus/**/*.{js,jsx}',
        'src/components/OrdersDashboardComponents/SettingsList/**/*.{js,jsx}',
        'src/components/OrdersDashboardComponents/CheckPassword/**/*.{js,jsx}',
        'src/components/OrdersDashboardComponents/BusinessProductsListing/**/*.{js,jsx}',
        'src/components/OrdersDashboardComponents/CityList/**/*.{js,jsx}',
        'src/components/OrdersDashboardComponents/CountryList/**/*.{js,jsx}',
        'src/components/OrdersDashboardComponents/ExportCSV/**/*.{js,jsx}',
        'src/components/OrdersDashboardComponents/GiftCardsList/**/*.{js,jsx}',
        'src/components/OrdersDashboardComponents/MetaFields/**/*.{js,jsx}',
        'src/components/OrdersDashboardComponents/PointsWalletLevels/**/*.{js,jsx}',
        'src/components/OrdersDashboardComponents/Appointments/**/*.{js,jsx}',
        'src/components/OrdersDashboardComponents/GoogleMapsApiKeySetting/**/*.{js,jsx}',
        'src/components/OrdersDashboardComponents/LogisticInformation/**/*.{js,jsx}',
        'src/components/OrdersDashboardComponents/Logistics/**/*.{js,jsx}',
        'src/components/OrdersDashboardComponents/ReviewCustomer/**/*.{js,jsx}',
        'src/components/OrdersDashboardComponents/Schedule/**/*.{js,jsx}'
      ],
      exclude: [
        'node_modules/',
        '**/*.config.{js,ts}',
        '**/setupTests.js',
        '**/*.{test,spec}.{js,jsx,ts,tsx}',
        '**/__tests__/**',
        '**/__mocks__/**',
        '**/coverage/**',
        '**/*.map',
        'src/sdk/lib/index.js',
        'src/sdk/lib/interfaces/**',
        'src/sdk/lib/types.js',
        'src/hooks/**',
        'native/**'
      ]
    }
  }
})
